from pydantic import BaseModel, EmailStr
from typing import List, Optional

# ------------------------------
# Premade Exercise
# ------------------------------
class BasePremadeExercise(BaseModel):
    name: str
    muscles: List[str]

class PremadeExercise(BasePremadeExercise):
    id: str  # uuid generated by Supabase

# ------------------------------
# Base Exercise (user exercise, no id)
# ------------------------------
class BaseExercise(BasePremadeExercise):
    user_email: EmailStr
    weight: int          # smallint
    weight_unit_lbs: bool
    sets: int            # smallint
    reps: int            # smallint
    pr: Optional[int] = None  # smallint, optional

# ------------------------------
# Exercise (read schema with id)
# ------------------------------
class Exercise(BaseExercise):
    id: str  # uuid generated by Supabase