from pydantic import BaseModel
from typing import List
from uuid import UUID

# ------------------------------
# Premade Plan (no id)
# ------------------------------
class PremadePlan(BaseModel):
    name: str
    interval: int          # smallint, number of days for the plan
    workouts: List[str]    # list of Workout IDs
    schedule: List[int]    # list of indexes in workouts list (length matches interval)

# ------------------------------
# Base Plan (user plan, no id)
# ------------------------------
class BasePlan(PremadePlan):
    # No additional fields for now
    pass

# ------------------------------
# Plan (read schema with id)
# ------------------------------
class Plan(BasePlan):
    id: str  # uuid generated by Supabase

    class Config:
        orm_mode = True