from pydantic import BaseModel, EmailStr
from typing import List

# ------------------------------
# Premade Plan (no id)
# ------------------------------
class BasePremadePlan(BaseModel):
    name: str
    interval: int          # smallint, number of days for the plan
    workouts: List[str]    # list of Workout IDs
    schedule: List[int]    # list of indexes in workouts list (length matches interval)

# ------------------------------
# Premade Plan (read schema with id)
# ------------------------------
class PremadePlan(BasePremadePlan):
    id: str  # uuid generated by Supabase

# ------------------------------
# Base Plan (user plan, no id)
# ------------------------------
class BasePlan(BasePremadePlan):
    user_email: EmailStr

# ------------------------------
# Plan (read schema with id)
# ------------------------------
class Plan(BasePlan):
    id: str  # uuid generated by Supabase