from pydantic import BaseModel, EmailStr
from typing import List

# ------------------------------
# Premade Workout (no id)
# ------------------------------
class BasePremadeWorkout(BaseModel):
    name: str
    exercises: List[str]  # list of Exercise IDs

# ------------------------------
# Premade Workout (read schema with id)
# ------------------------------
class PremadeWorkout(BasePremadeWorkout):
    id: str  # uuid generated by Supabase

# ------------------------------
# Base Workout (user workout, no id)
# ------------------------------
class BaseWorkout(BasePremadeWorkout):
    user_email: EmailStr
    pass

# ------------------------------
# Workout (read schema with id)
# ------------------------------
class Workout(BaseWorkout):
    id: str  # uuid generated by Supabase