// ------------------------------
// Premade Exercise
// ------------------------------
export interface BasePremadeExercise {
  name: string;
  muscles: string[];
}

export interface PremadeExercise extends BasePremadeExercise {
  id: string; // uuid generated by Supabase
}

// ------------------------------
// Base Exercise (user exercise, no id)
// ------------------------------
export interface BaseExercise extends BasePremadeExercise {
  user_email: string; // EmailStr → string
  weight: number; // smallint
  weight_unit_lbs: boolean;
  sets: number; // smallint
  reps: number; // smallint
  pr?: number | null; // optional
}

// ------------------------------
// Exercise (read schema with id)
// ------------------------------
export interface Exercise extends BaseExercise {
  id: string; // uuid generated by Supabase
}