from pydantic import BaseModel
from typing import List

# ------------------------------
# Premade Workout (no id)
# ------------------------------
class PremadeWorkout(BaseModel):
    name: str
    exercises: List[str]  # list of Exercise IDs

# ------------------------------
# Base Workout (user workout, no id)
# ------------------------------
class BaseWorkout(PremadeWorkout):
    # No additional fields for now
    pass

# ------------------------------
# Workout (read schema with id)
# ------------------------------
class Workout(BaseWorkout):
    id: str  # uuid generated by Supabase

    class Config:
        orm_mode = True